---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: Universität Osnabrück
subtitle: Digitale Dienste
logo: uos-logo.png
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: '#ae0f35'
    highlight-secondary: "#ba223e"
    highlight-hover: "#dd3344"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#ae0f35"
    highlight-secondary: "#ba223e"
    highlight-hover: "#dd3344"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Demo !"
  icon: "fa fa-grin"
  content: "This is a dummy homepage demo."

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: Uni Webseite
    icon: fab fa-bell-concierge
    url: https://uni-osnabrueck.de
    target: "_blank" # optional html a tag target attribute

  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  - name: Verwaltung
    icon: "fas fa-book"
    url: "#additional-page"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: Kommunikation
    icon: "fas fa-cloud"
    items:
      - name: Matrix
        logo: https://www.svgrepo.com/show/342019/matrix.svg
        subtitle: Föderierter Chat
        tag: "app"
        keywords: "self hosted reddit"
        url: https://chat.uni-osnabrueck.de
        target: "_blank" # optional html a tag target attribute

      - name: Sogo
        logo: https://www.svgrepo.com/show/331580/sogo.svg
        subtitle: E-Mail, Kalender und Kontakte
        tag: "app"
        url: https://sogo.uni-osnabrueck.de

      - name: BigBlueButton
        logo: https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/BigBlueButton_icon.svg/1024px-BigBlueButton_icon.svg.png
        subtitle: Videokonferenz und Onlinelehre
        tag: "app"
        url: https://webconf.uni-osnabrueck.de

  - name: Lehre
    icon: fas person-chalkboard
    items:
      - name: Stud.IP
        logo: https://gitlab.studip.de/uploads/-/system/project/avatar/42/android-chrome-256x256.png
        subtitle: Lernmanagement & Kurse
        tag: "app"
        keywords: "self hosted reddit"
        url: https://studip.uni-osnabrueck.de
        target: "_blank" # optional html a tag target attribute

      - name: Opencast
        logo: https://opencast.org/wp-content/uploads/2020/12/opencast-logo.png?w=240
        subtitle: Vorlesungsaufzeichnungen
        tag: "app"
        url: "#"

  - name: Dokumente und Dateien
    icon: "fas fa-cloud"
    items:
      - name: HedgeDoc
        logo: https://avatars.githubusercontent.com/u/67865462?s=280&v=4
        subtitle: Kollaborative Notizen
        tag: docs
        keywords: "self hosted reddit"
        url: https://hedgedoc.uni-osnabrueck.de
        target: "_blank" # optional html a tag target attribute

      - name: MyShare
        logo: "assets/tools/sample2.png"
        subtitle: Onlinespeicher
        tag: "app"
        url: https://myshare.uni-osnabrueck.de
